version: "3.8"
services:
    fhir-data-processor:
        container_name: fhir-ingestor
        image: fhir-ingestion:latest
        env_file: .env
        environment:
            MONGO_URI: $MONGO_URI
        volumes:
            - ${PSQL_SSL_ROOT_CERT}:/app/${PSQL_SSL_ROOT_CERT}
